workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - flutter clean
      - flutter pub get
      - cd ios
      - pod install --repo-update
      - cd ..
      - flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa